### ISSUE TITLE
Consuming Kafka Messages

### ISSUE THREAD

**Issue by jtruelove** [zanox/mod-kafka#7]
Does this module allow for consuming kafka messages at all then or is just for producing them? Seems like you still need to write a separate consuming verticle to actually get messages that you could then put on the event bus.

**Comment by mariamhakobyan-zanox** [comment]
Hi @jtruelove,

This open source module only produces messages to Kafka. You are right, we have an additional application, which sends messages to Vert.x's Event Bus, and then this module reads messages from Event Bus, and sends them to Kafka.

Mariam
